47/publish
graasp/graasp-cli pull request #49
Opened 2020-09-03 09:52 UTC by pyphilia

This draft only contains the process to zip the build folder of a given app.

2020-09-03 11:17 UTC, juancarlosfarah requested changes
@pyphilia, can you please merge the other branch and rebase so that I can see only the changes relevant here?

2020-09-03 11:23 UTC, juancarlosfarah requested changes
I was able to filter the commits. Very nice! I like it. Have a look at my comments. Just some minor stuff.

2020-09-03 11:23 UTC, juancarlosfarah commented on src/createPackageFile.js
> +const BUILD_PACKAGE_NAME = 'package.zip';
Factor out to config.

2020-09-03 11:23 UTC, juancarlosfarah commented on src/createPackageFile.js
> +    archive.on('error', (err) => {
Does this `throw` on error? Or does it still `pipe` and `directory`?

2020-09-03 11:23 UTC, juancarlosfarah commented on src/createPackageFile.js
> +        console.error(err);
Use `warning`?

2020-09-03 11:23 UTC, juancarlosfarah commented on src/createCli.js
> +        command: 'publish',
Shall we call this `package`? Because for `publish` we might want to do some more stuff later.

2020-09-03 11:23 UTC, juancarlosfarah commented on src/createCli.js
> +        desc: 'Publish a zipped app',
Add `.` for consistency with 'Create new Graasp app.' (or remove dot elsewhere).

2020-09-03 11:23 UTC, juancarlosfarah commented on src/createPackageFile.js
> +    const buildDirPath = `${DEFAULT_PATH}/${BUILD_DIRECTORY}`;
Here you have `//` with the current `BUILD_DIRECTORY` value/

2020-09-03 14:59 UTC, pyphilia commented
I changed `publish` into `package`. If you're okay with this command, we can also merge this as a PR.

2020-09-04 10:01 UTC, juancarlosfarah commented
Can you mark it as ready to review @pyphilia ?

2020-09-18 09:55 UTC, juancarlosfarah approved these changes
Looks good! Just the question I mentioned before about throwing.

2020-09-18 15:17 UTC, juancarlosfarah requested changes
@pyphilia, very nice. Just a minor thing to remove.

2020-09-18 15:17 UTC, juancarlosfarah commented on src/createPackageFile.js
> +    // const output = 'wef';
@pyphilia need to delete this.

2020-09-24 08:26 UTC, juancarlosfarah commented on src/createPackageFile.js
> +    // const output = 'wef';
@pyphilia, I think that this minor thing is still pending, right?

2020-09-28 14:25 UTC, merged